### ISSUE TITLE
Removing ralf sometimes fails

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/ralf#168]
When uninstalling ralf, it sometimes fails when removing /var/lib/ralf/ralf.conf because it no longer exists, so I made the prerm script ignore the error like so:
```
88c88
<         rm -f /var/lib/$NAME/$NAME.conf
---
>         rm /var/lib/$NAME/$NAME.conf
```

**Comment by eleanor-merry** [comment]
This fix also needs to be made for Homestead and the alarms-agent
