### ISSUE TITLE
ENT log not issued when sas_server not set

### ISSUE THREAD

**Issue by dcollins991** [Metaswitch/ralf#181]
For test case, ENT-CL_SPROUT_INVALID_SAS_OPTION, the sas_server option is removed from the shared_config file, the file is uploaded, and Ralf is restarted. Ralf no longer issues the ENT log beginning with, "The sas_server option in /etc/clearwater/config is invalid or not configured...". However a Warning is issued in the Ralf log. Paradoxically Homestead does issue the ENT log when the sas_server option is removed. The issue was detected during V8 regression testing. The issue can be reproduced by removing the sas_server line in shared_config, uploading the shared_config file, and then restarting Ralf.

**Comment by mirw** [comment]
Thanks for raising this.

It looks like we only generate this log if you try to set `sas_server` to an invalid value - in particular, explicitly setting it to blank or setting it to something containing a ','.  Not setting `sas_server`at all will not cause this log.

I suspect we should just fix up the log text to remove the "or not configured".

I'm surprised that Ralf outputs a log in this case - its code looks identical in this area.  @dcollins991, can you share what the Ralf log looks like, and also let me know what the command-line arguments to ralf are (by running `ps -eaf | grep ralf`)?

@JimBunch, I'm guessing this isn't critical - please fix if it is.

**Comment by JimBunch** [comment]
This is not a critical issue.

**Comment by graemerobertson** [comment]
I think we must have fixed this because I can't repro it.
