### ISSUE TITLE
Accounting-Record-Number AVP for INVITE session ACRs does not increment correctly

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/ralf#182]
When looking at the Accounting-Record-Number AVPs for ACRs in an INVITE session the following was observed for a 3 minute call with 45S session refresh:

Orig S-CSCF Session:
    start = 1
    interims = 2,3,4,5,6,7,8,9,10
    stop = 10

Term S-CSCF Session:
    start = 1
    interims = 2,3,4,5,6,6,6,7,8
    stop = 7

A tcpdump of the Rf interface at the CCF will be uploaded.

**Comment by mirw** [comment]
@JimBunch, assuming this isn't critical - please correct if not!

**Comment by JimBunch** [comment]
Not critical.

**Comment by graemerobertson** [comment]
https://github.com/Metaswitch/ralf/pull/183 and https://github.com/Metaswitch/ralf/pull/184 will resolve these issues I believe

**Comment by graemerobertson** [comment]
With just https://github.com/Metaswitch/ralf/pull/183, you may still see one issue (if you hit a small window). It's fixed completely in #184.

Using your example above, you might see something like the following with just #183.

Orig S-CSCF Session:
start = 1
interims = 2,3,4,5,6,7,8,9,10
stop = 11

Term S-CSCF Session:
start = 1
interims = 2,3,4,5,6,7,8,9,10
stop = 10

**Comment by graemerobertson** [comment]
@JimBunch, as per my email, I think at least half of this issue is critical

**Comment by graemerobertson** [comment]
@plfrancis Alex has pointed out that currently #184 will actually have no effect so this isn't quite completely fixed. I'll take it back.

#183 is still critical.

**Comment by graemerobertson** [comment]
I see #183 has been taken, so I'm going to downgrade the status of this issue again.

**Comment by plfrancis** [comment]
I've confirmed that #183 resolves the INTERIM sequence issue. I did not observe a problem with the STOP sequence in release-85, but will leave this open for a fix to the 'small window' issue discussed above.

**Comment by JimBunch** [comment]
Marked as critical because it affects the accuracy of billing,

**Comment by graemerobertson** [comment]
This fix is now complete, and since @plfrancis couldn't repro the problem with the original half fix, I've closed this issue.
