### ISSUE TITLE
Stuck RALF_PROCESS_FAIL alarm

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/ralf#238]
Stuck ```RALF_PROCESS_FAIL``` alarm

#### Symptoms

When deploying a system I invariably end up with a stuck ```RALF_PROCESS_FAIL``` alarm on one or more ralf nodes.

#### Impact

Confusion since the ralf process is actually up and running.

#### Release and environment 

release-103

#### Steps to reproduce
1) Freshly deploy a system and look for stuck ```RALF_PROCESS_FAIL``` alarms.

    OR get the same effect by doing this:

1) monit restart ralf_process
2) sleep 25
3) stop clearwater-monit
4) sleep 10
5) start clearwater-monit

I don't know the root cause of the problem, but I can remedy it with the following change to ralf's monit script:

```
diff --git a/ralf.root/usr/share/clearwater/infrastructure/scripts/ralf.monit b/ralf.root/usr/share/clearwater/infrastructure/scripts/ralf.monit
index a241bd0..f0d0f99 100755
--- a/ralf.root/usr/share/clearwater/infrastructure/scripts/ralf.monit
+++ b/ralf.root/usr/share/clearwater/infrastructure/scripts/ralf.monit
@@ -53,10 +53,10 @@ check process ralf_process with pidfile /var/run/ralf/ralf.pid
   # generate a core file and trigger diagnostics collection.
   if memory > 80% for 6 cycles then exec "/bin/bash -c '/usr/share/clearwater/bin/issue-alarm monit 2000.3; /etc/init.d/ralf abort'"
 
-  # Clear any alarms if the process has been running for 30 seconds
-  if uptime < 30 seconds
-     then exec "/bin/true"
-     else if succeeded then exec "/usr/share/clearwater/bin/issue-alarm monit 2000.1"
+check program uptime_ralf with path "/usr/share/clearwater/bin/check-uptime /var/run/ralf/ralf.pid monit 2000.1"
+  group ralf
+  depends on ralf_process
+  every 3 cycles
+  if status != 0 then alert
 
 # Check the HTTP interface. This depends on the Ralf process (and so won't run
 # unless the Ralf process is running)
```

Diags are available.

**Comment by eleanor-merry** [comment]
Yes, it looks like Ralf missed getting an uptime script. Fix is as you suggest (adding the ralf_uptime program). Fixer should also check the other processes to see if any were missed

**Comment by sathiyan-sivathas** [comment]
Adding to the list of things that the fixer should look at, they should also see why Monit doesn't start the ralf process.  That was covered by the issue that Rob references above, but it makes sense for the two to be looked at together.

**Comment by sathiyan-sivathas** [comment]
@eleanor-merry You're right, the Monit doesn't start the ralf process bug is specific to the split-storage packaging branches.  Fixing that should be covered by the follow on packaging story, so you can ignore what I wrote above.
