### ISSUE TITLE
Ralf recycles Diameter connections as regularly as every 5 seconds despite a much longer DNS TTL

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/ralf#265]
#### Symptoms
I saw Ralf recycling its Diameter connections every 5 seconds.

This looks like it's because the [DiameterResolver's resolve()](https://github.com/Metaswitch/cpp-common/blob/master/src/diameterresolver.cpp#75) function basically always returns 0 as the TTL (and then the RealmManager changes it to 5 seconds).

I've attached debug logs (I turned them on at 09:35). The one odd thing is that we don't seem to hit this in the first 2 minutes after coming up (which is correct - that's the DNS TTL), but then we start seeing this behaviour every 5 seconds after that. I can't work out what's different about the first time we call resolve...

#### Impact
As far as I know this doesn't cause any impact beyond being confusing, but we are just doing more work than we need to which can't be a good thing. 

#### Release and environment 
CC-ralf-10.0.0-170211-~255.00.0.ova on VMware, three CDFs.

#### Steps to reproduce
Provide Ralf with a billing room with 3+ CDFs that it can connect to.

**Comment by graemerobertson** [comment]
Also (almost certainly) affects Homestead

**Comment by mirw** [comment]
Are we also not impacting the HSS and CDF?  I can believe that they'd get log spam too (and possibly even alarms).  @chris-elford-metaswitch, should this be higher priority?

**Comment by graemerobertson** [comment]
It's an interesting question. A couple of thoughts...
* Even when this is WAD and DNS TTL is set to something very large we resolve the billing realm and possibly recycle diameter connections every 5 minutes anyway, so whilst this issue accentuates problems like the ones you suggest, they are still present when WAD. (Obviously that could just mean that the design is wrong!)
* I wouldn't expect the HSS or CDF to alarm. For example, if you have a pool of CDFs then not having a connection to one of them is not an alarmable condition - it's perfectly legitimate.

**Comment by graemerobertson** [comment]
@KristaHyer I've tested with the new packages you pointed me at and I can confirm that this is fixed - I'm happy for you to close once you've checked the code in.
